### ISSUE TITLE
OpenFL doesn't setup; lime won't download.

### ISSUE THREAD

**Issue by jimmymathews** [MetaStudents/OldSchoolSim#1]
I'm on Ubuntu 18.04. I think I installed haxelib successfully. This line fails repeatedly:

```
haxelib run openfl setup

Downloading lime-6,4,0.zip...
Download complete : 0 bytes in 10.1s (0KB/s)
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout
Error: Library lime is not installed
```

**Comment by meygerjos** [comment]
[This repository is deprecated](https://github.com/MetaStudents/OldSchoolSim/blob/master/README.md).  See [the corresponding issue on the new version](https://github.com/MetaStudents/SchoolSim/issues/10).
